import numpy

#Main
FPS = 60

#Map stuff
CELLSIZE = 47
WIDTH, HEIGHT = 1500, 982
HALF_WIDTH = WIDTH//2
HALF_HEIGHT = HEIGHT//2
ROWS = HEIGHT//CELLSIZE
COLS = WIDTH//CELLSIZE

# Raycasting stuff
FOV = numpy.pi/5
HALF_FOV = FOV/2
NUM_RAYS = WIDTH//2
HALF_NUM_RAYS = NUM_RAYS//2
DELTA_ANGLE = FOV/NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH / numpy.tan(HALF_FOV)
SCALE = WIDTH//NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2